---
- name: get hostname
  win_shell: echo %COMPUTERNAME%
  args:
    executable: cmd.exe
  register: win_server_hostname

- name: get os version
  win_shell: |
    $osVer=(Get-ItemProperty "HKLM:\Software\Microsoft\Windows NT\CurrentVersion").ProductName
    Write-Output $osVer.Trim()
  register: win_server_osname

- name: result / set_fact
  set_fact:
    act_result: {
      'doc': {
        'hostname': "{{ win_server_hostname.stdout_lines.0 }}",
        'osVer': "{{ win_server_osname.stdout_lines.0 }}"
      }
    }

- name: insert result
  ansible.builtin.uri:
    url: "{{ post_win_server_patch_update_url }}"
    user: "elastic"
    password: "elastic1234"
    method: POST
    headers:
      Content-Type: application/json
      Accept: application/json
#       body_format: classesRating_mapping.json
    body_format: json
    body:
      "{{ act_result }}"
    validate_certs: no
    status_code: 200,201
    timeout: 10
  delegate_to: localhost
